modLoader = "javafml" #mandatory
loaderVersion = "[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GNU Lesser General Public License"
[[mods]] #mandatory
modId = "aeinfinitybooster" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "AEInfinityBooster" #mandatory
description = '''

'''
[[dependencies.aeinfinitybooster]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[40,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.aeinfinitybooster]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.aeinfinitybooster]]
modId = "ae2"
versionRange = "[11.0.0-alpha.4,)"
mandatory = true
ordering = "AFTER"
side = "BOTH"